#!/bin/bash
set -e

# apt-get install -y wget

cd /tmp

wget -O cmake-installer https://cmake.org/files/v3.15/cmake-3.15.0-rc1-Linux-x86_64.tar.gz
mkdir -p ~/kitware
tar -C ~/kitware -xzf cmake-installer

mv ~/kitware/cmake-3.15.0-rc1-Linux-x86_64 ~/kitware/cmake
export PATH=~/kitware/cmake/bin:$PATH

# apt-get install -y python3-pip python3-setuptools

mkdir -p ~/kitware/autopybind11

pip3 install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple autopybind11
autopybind11-cmake --dir ~/kitware/autopybind11

export APB=~/kitware/autopybind11
